import { useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, Mail, MessageCircle, Phone, RefreshCw, ShieldCheck, X } from "lucide-react";
import { Link } from "wouter";

type Item = { id: string; url: string; name: string; contactPerson: string; status: string; priority: string; channel: string; contact: string; reason: string; draft: string; overdue: boolean; requiresHumanApproval: boolean };
type Plan = { scanned: number; candidates: number; byChannel: Record<string, number>; exclusions: Record<string, number>; safety: { cooldownDays: number; humanApprovalRequired: boolean; sendsPerformed: number; phoneNumbersAreNotTreatedAsWhatsAppConsent: boolean }; items: Item[] };

const icons: Record<string, any> = { email: Mail, whatsapp: MessageCircle, phone: Phone };

export default function OutreachMission() {
  const [token, setToken] = useState(() => sessionStorage.getItem("firstline_ops_token") || "");
  const [draftToken, setDraftToken] = useState(token);
  const [plan, setPlan] = useState<Plan | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [selected, setSelected] = useState<Item | null>(null);

  async function run(activeToken = token) {
    if (!activeToken) return;
    setLoading(true); setError("");
    try {
      const response = await fetch("/api/ops/outreach-plan", { headers: { Authorization: `Bearer ${activeToken}` }, cache: "no-store" });
      if (!response.ok) throw new Error(response.status === 401 ? "Invalid operations key." : "Unable to prepare outreach plan.");
      setPlan(await response.json());
    } catch (e) { setError(e instanceof Error ? e.message : "Unable to prepare outreach plan."); }
    finally { setLoading(false); }
  }

  function unlock() { const next = draftToken.trim(); if (!next) return; sessionStorage.setItem("firstline_ops_token", next); setToken(next); run(next); }

  if (!token || !plan) return <main className="min-h-screen bg-[#0D2037] px-5 py-12 text-white sm:px-8"><div className="mx-auto max-w-lg pt-16"><Link href="/ops" className="text-xs font-bold text-slate-300">← Command Centre</Link><div className="mt-8 mb-8 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center bg-[#B8121C]"><ShieldCheck size={21} /></span><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#F5B8BB]">FirstLine Mission</p><h1 className="font-display text-3xl">Outreach Planner</h1></div></div><div className="border border-white/15 bg-white/5 p-6"><p className="text-sm leading-6 text-slate-300">Scan Hubil Clients, identify safe follow-up candidates, and prepare personalized drafts. No messages are sent by this mission.</p><input value={draftToken} onChange={e => setDraftToken(e.target.value)} onKeyDown={e => e.key === "Enter" && unlock()} type="password" placeholder="Operations key" className="mt-5 w-full border border-white/15 bg-black/20 px-4 py-3 text-sm outline-none focus:border-[#E14C53]" /><button onClick={unlock} disabled={!draftToken.trim() || loading} className="mt-3 flex w-full items-center justify-center gap-2 bg-[#B8121C] px-4 py-3 text-sm font-extrabold disabled:opacity-50">{loading ? <RefreshCw className="animate-spin" size={17} /> : <ShieldCheck size={17} />} Run safe outreach scan</button>{error && <p className="mt-4 text-sm text-[#F5B8BB]">{error}</p>}</div></div></main>;

  return <main className="min-h-screen bg-[#F8F6F1] text-[#0D2037]"><header className="border-b border-[#D8D4CC] bg-[#0D2037] px-5 py-5 text-white sm:px-8"><div className="mx-auto flex max-w-[1400px] items-center justify-between"><div><Link href="/ops" className="text-xs font-bold text-slate-300">← Command Centre</Link><p className="mt-3 text-[0.6rem] font-extrabold uppercase tracking-[0.18em] text-[#F5B8BB]">FirstLine Mission</p><h1 className="font-display text-3xl">Outreach Planner</h1></div><button onClick={() => run()} disabled={loading} className="inline-flex items-center gap-2 border border-white/20 px-3 py-2 text-xs font-bold">{loading ? <RefreshCw className="animate-spin" size={15} /> : <RefreshCw size={15} />} Rescan</button></div></header><div className="mx-auto max-w-[1400px] px-5 py-8 sm:px-8">
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Scanned", plan.scanned], ["Candidates", plan.candidates], ["Email", plan.byChannel.email ?? 0], ["WhatsApp", plan.byChannel.whatsapp ?? 0]].map(([label, value]) => <article key={label as string} className="border border-[#D8D4CC] bg-white p-5"><p className="text-[0.6rem] font-extrabold uppercase tracking-[0.16em] text-[#526174]">{label}</p><p className="mt-2 font-display text-4xl">{value}</p></article>)}</section>
    <div className="mt-6 flex flex-wrap gap-3 border border-[#D8D4CC] bg-white p-5 text-xs text-[#526174]"><span className="inline-flex items-center gap-2"><Clock3 size={14} /> {plan.safety.cooldownDays}-day cooldown</span><span className="inline-flex items-center gap-2"><ShieldCheck size={14} /> Human approval required</span><span className="inline-flex items-center gap-2"><CheckCircle2 size={14} /> {plan.safety.sendsPerformed} sends performed</span></div>
    <section className="mt-6 border border-[#D8D4CC] bg-white"><div className="border-b border-[#D8D4CC] px-5 py-4"><h2 className="font-extrabold">Prepared outreach</h2><p className="mt-1 text-xs text-[#526174]">Every item is a draft only. Review before any external communication.</p></div>{plan.items.length === 0 ? <div className="p-12 text-center"><CheckCircle2 className="mx-auto" size={28}/><p className="mt-3 font-bold">No safe outreach candidates right now.</p></div> : <div className="divide-y divide-[#D8D4CC]">{plan.items.map(item => { const Icon = icons[item.channel] ?? Phone; return <button key={item.id} onClick={() => setSelected(item)} className="grid w-full gap-3 px-5 py-5 text-left hover:bg-[#F8F6F1] lg:grid-cols-[1fr_0.8fr_1.5fr_auto] lg:items-center"><div><p className="font-extrabold">{item.name}</p><p className="mt-1 text-xs text-[#526174]">{item.contactPerson || item.contact}</p></div><div className="flex items-center gap-2 text-xs font-bold"><Icon size={15}/>{item.channel}</div><p className="text-xs leading-5 text-[#526174]">{item.reason}</p><span className="text-xs font-extrabold text-[#B8121C]">Review →</span></button> })}</div>}</section>
    {selected && <div className="fixed inset-0 z-50 bg-black/40 p-4" onClick={() => setSelected(null)}><aside onClick={e => e.stopPropagation()} className="ml-auto h-full w-full max-w-xl overflow-y-auto bg-white p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-[0.6rem] font-extrabold uppercase tracking-[0.16em] text-[#B8121C]">Draft review</p><h2 className="mt-1 font-display text-3xl">{selected.name}</h2></div><button onClick={() => setSelected(null)} className="border border-[#D8D4CC] p-2"><X size={18}/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="border border-[#D8D4CC] p-4"><p className="text-[0.58rem] font-extrabold uppercase text-[#526174]">Stage</p><p className="mt-1 text-sm font-bold">{selected.status}</p></div><div className="border border-[#D8D4CC] p-4"><p className="text-[0.58rem] font-extrabold uppercase text-[#526174]">Channel</p><p className="mt-1 text-sm font-bold">{selected.channel}</p></div></div><div className="mt-5 border border-[#D8D4CC] bg-[#F8F6F1] p-5"><p className="text-[0.58rem] font-extrabold uppercase tracking-[0.14em] text-[#526174]">Prepared message</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{selected.draft}</p></div><div className="mt-5 flex items-start gap-2 text-xs leading-5 text-[#526174]"><ShieldCheck size={15} className="mt-0.5 shrink-0"/>This screen prepares communication only. It does not send. Phone numbers are not treated as WhatsApp consent.</div>{selected.url && <a href={selected.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 bg-[#0D2037] px-4 py-3 text-sm font-extrabold text-white">Open Notion record</a>}</aside></div>}
  </div></main>;
}
